name: 'youtube_analytics'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  youtube_analytics:
    channel_basic: "{{ ref('stg_youtube__channel_basic') }}"
    channel_demographics: "{{ ref('stg_youtube__channel_demographics') }}"
    video: "{{ ref('stg_youtube__video') }}"
models:
  youtube_analytics:
    +materialized: table
    +schema: youtube
    intermediate:
      +materialized: ephemeral
    staging:
      +schema: youtube_analytics_source
      +materialized: view
