name: 'youtube_analytics'
version: '1.0.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  youtube_analytics:
    channel_basic: "{{ source('youtube_analytics','channel_basic_a_2') }}"
    channel_demographics: "{{ source('youtube_analytics','channel_demographics_a_1') }}"
    video: "{{ source('youtube_analytics','video') }}"

models:
  youtube_analytics:
    +materialized: table
    +schema: youtube
    intermediate:
      +materialized: ephemeral
    staging:
      +schema: youtube_source
      tmp:
        +materialized: view
